name: HXL Recipes

on:
  push:
    branches:
      - dev
      
permissions:
  contents: write  # Needed to push changes
  pages: write     # Needed to create GitHub Pages deployments
  id-token: write  # Needed for identity token (OIDC)

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.15'

      - name: List JSON files
        run: ls -l recipes/*json

      - name: Run script
        run: cd run; python3 run.py

      - name: Copy index.html
        run: cp run/index.html recipes/

      - name: Debug
        run: ls -l recipes/*; pwd

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'recipes'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
